name: curare
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
   - snakemake=7.32.3
   - mamba=1.5.3
   - python=3.10
   - pyyaml=6.0.1
   - docopt=0.6.2
   - progressbar2=4.3.2
   - biopython=1.83

